import Head from 'next/head'
import { Container, Typography, Box, Grid, Paper, Link } from '@mui/material'
import Image from 'next/image'

import Performance from '@/components/Performance'
import StockTable from '@/components/StockTable'
import Value from '@/components/Value'

export default function Home() {
  return (
    <>
      <Head>
        <title>TraderNest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ display: 'flex' }}>
          <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <Paper
                  sx={{
                    p: 8,
                    display: 'flex',
                    flexDirection: 'row',
                    alignItems: 'center',
                  }}
                >
                  <Typography
                    component="h1"
                    variant="h2"
                    sx={{
                      fontWeight: 'bold',
                    }}
                  >
                    Keep track of everything in one place
                  </Typography>
                  <Image src="/6963.jpg" width={480} height={300} alt="" />
                </Paper>
              </Grid>
              <Grid item xs={12} md={8} lg={9}>
                <Performance />
              </Grid>
              <Grid item xs={12} md={4} lg={3}>
                <Value />
              </Grid>
              <Grid item xs={12}>
                <StockTable />
              </Grid>
            </Grid>
          </Container>
        </Box>
      </main>
    </>
  )
}
