import Head from 'next/head'

import { Container, Box, Grid } from '@mui/material'

import StockTable from '@/components/StockTable'
const finnhub = require('finnhub')

const api_key = finnhub.ApiClient.instance.authentications['api_key']
api_key.apiKey = process.env.FINNHUB_API_KEY
const finnhubClient = new finnhub.DefaultApi()

export default function Portfolio() {
  finnhubClient.quote('AAPL', (error: any, data: any, response: any): void => {
    console.log(data)
  })

  return (
    <>
      <Head>
        <title>TraderNest Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ display: 'flex' }}>
          <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <StockTable />
              </Grid>
            </Grid>
          </Container>
        </Box>
      </main>
    </>
  )
}
